### ISSUE TITLE
Error when opening project in Unity

### ISSUE THREAD

**Issue by acesolucoes** [keijiro/Dcam2#1]
The ML.asmdef references a platform not yet known:

![image](https://github.com/user-attachments/assets/48f6af05-5a0d-45c7-8f01-52b5c3773783)

I had to delete the reference editing the .asmdef file by hand inorder to fully load the project without errors. 
Is this plaform (MacOSStandaloneServer) available on Mac? Or is it something not launched yet?

**Comment by keijiro** [comment]
Sorry. This project is under construction. It's not expected to work.
